import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-repertorio',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './repertorio.component.html',
  styleUrl: './repertorio.component.css'
})
export class RepertorioComponent implements OnInit {
  categories = [
    'Las más románticas', //Para serenata
    'Las llegadoras', // Dolidas
    'Echando bailongo', // Para bailar
    'Para recordar mis ayeres', // Viejitas
    'Canciones para misa', // Misas
    'Una última despedida', // Velorios
  ];

  songs = [
    { title: 'Cien Años', artist: 'Pedro Infante', category: 'Las más románticas' },
    { title: 'Si Dios Me Quita la Vida', artist: 'Javier Solís', category: 'Las más románticas' },
    { title: 'Te Prometo', artist: 'Mariachi Vargas', category: 'Las más románticas' },
    { title: 'Hasta mi Final', artist: "Il Divo", category: 'Las más románticas' },
    { title: 'Contigo Aprendí', artist: "Tradicional", category: 'Las más románticas' },
    { title: 'Dime Cómo Quieres', artist: "Christian Nodal y Ángela Aguilar", category: 'Las más románticas' },
    { title: 'Hermoso Cariño', artist: "Vicente Fernández", category: 'Las más románticas' },
    { title: 'Regalo de Dios', artist: "Julión Álvarez", category: 'Las más románticas' },
    { title: 'Hasta Dónde Te Quiero', artist: "La Rondalla de Saltillo", category: 'Las más románticas' },
    { title: 'Me Gustas Mucho', artist: "Rocio Durcal", category: 'Las más románticas' },
    { title: 'El Milagro de tus Ojos', artist: "José Julián", category: 'Las más románticas' },
    { title: 'Serenta Huasteca', artist: "Luis Miguel", category: 'Las más románticas' },
    { title: 'Deja que Salga la Luna', artist: "Pedro Infante", category: 'Las más románticas' },
    { title: 'Eso y Más', artist: "Joan Sebastian", category: 'Las más románticas' },
    { title: 'El Primer Tonto', artist: "Joan Sebastian", category: 'Las más románticas' },
    { title: 'Bésame Mucho', artist: "Tradicional", category: 'Las más románticas' },
    { title: 'Solamente La Mano de Dios', artist: "José Alfredo Jiménez", category: 'Las más románticas' },
    { title: 'Sabor a Mí', artist: "Luis Miguel", category: 'Las más románticas' },
    { title: 'Sabes una Cosa', artist: "Luis Miguel", category: 'Las más románticas' },
    { title: 'El Reloj', artist: 'Luis Miguel', category: 'Las más románticas' },
    { title: 'Usted', artist: 'Luis Miguel', category: 'Las más románticas' },
    { title: 'Cuando Tú Me Besas', artist: 'Bebeto', category: 'Las más románticas' },
    { title: 'Toda una Vida', artist: 'Antonio Machín', category: 'Las más románticas' },
    { title: 'Muñequita Linda', artist: 'Los Panchos', category: 'Las más románticas' },
    { title: 'Ojos Cafés', artist: 'Trío Monterrey', category: 'Las más románticas' },
    { title: 'Morenita Mía', artist: 'Los Tres Ases', category: 'Las más románticas' },
    { title: 'Nuestro Juramento', artist: 'Julio Jaramillo y Rosalino Quintero y su Conjunto', category: 'Las más románticas' },
    { title: 'Embrujo', artist: 'Los Tres Diamantes', category: 'Las más románticas' },
    { title: 'Despierta', artist: 'Pedro Infante', category: 'Las más románticas' },
    { title: 'Entrega Total', artist: 'Javier Solís', category: 'Las más románticas' },
    { title: '3 Regalos', artist: 'Los Dandy`s', category: 'Las más románticas' },
    { title: 'Anillo de Compromiso', artist: 'Cuco Sánchez', category: 'Las más románticas' },
    { title: 'Vestida de Blanco', artist: 'Rocío Dúrcal', category: 'Las más románticas' },
    { title: 'En Tu Pelo', artist: 'Javier Solís', category: 'Las más románticas' },
    { title: 'Amanecí Entre Tus Brazos', artist: 'José Alfredo Jiménez', category: 'Las más románticas' },
    { title: 'Loco', artist: 'Los Auténticos Decadentes', category: 'Las más románticas' },
    { title: 'Amorcito Corazón', artist: 'Pedro Infante', category: 'Las más románticas' },
    { title: 'Novia Mía', artist: 'Salvador Guerrero y Carlos Castellanos', category: 'Las más románticas' },
    { title: 'Esta Noche Voy a Verla', artist: 'Juan Gabriel', category: 'Las más románticas' },
    { title: 'Las Llaves de Mi Alma', artist: 'Vicente Fernández', category: 'Las más románticas' },
    { title: 'Amarte a la Antigüa', artist: 'Pedro Fernández', category: 'Las más románticas' },
    { title: 'Serenata Sin Luna', artist: 'Antonio Aguilar', category: 'Las más románticas' },
    { title: 'Mi Mayor Anhelo', artist: 'Banda MS', category: 'Las más románticas' },
    { title: 'Un Motivo', artist: 'Vicente Fernández', category: 'Las más románticas' },
    { title: 'Yo Quiero Ser', artist: 'Yo Quiero Ser', category: 'Las más románticas' },
    { title: 'Si Nos Dejan', artist: 'Luis Miguel', category: 'Las más románticas' },
    { title: 'Gema', artist: 'Los Dandy`s', category: 'Las más románticas' },
    { title: 'Que Bonito Amor', artist: 'Vicente Fernández', category: 'Las más románticas' },
    { title: 'Si Quieres', artist: 'Juan Gabriel', category: 'Las más románticas' },
    { title: 'Cariño Mío (Yo No Sé Vivir Sin Ti)', artist: 'Luis Jara', category: 'Las más románticas' },
    { title: 'Mi Razón de Ser', artist: 'Banda MS', category: 'Las más románticas' },

    { title: 'Cucurucucú Paloma', artist: 'Rocío Durcal', category: 'Las llegadoras' },
    { title: 'Sin Ti', artist: 'Mariachi Vargas', category: 'Las llegadoras' },
    { title: 'Mucho Corazón', artist: 'Luis Miguel', category: 'Las llegadoras' },
    { title: 'Disculpe Usted', artist: 'Los Rayos del Norte y Sergio Vega', category: 'Las llegadoras' },
    { title: 'Las Rejas No Matan', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'Pan Todo el Año', artist: 'José Alfredo Jiménez', category: 'Las llegadoras' },
    { title: 'Esta Tristeza Mía', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'Con Mis Propias Manos', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'El Mal Querido', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'Bésame y Olvídame', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'Renunciación', artist: 'Javier Solís', category: 'Las llegadoras' },
    { title: 'Abrázame', artist: 'Alejandro Fernández', category: 'Las llegadoras' },
    { title: 'Niña Amada Mía', artist: 'Alejandro Fernández', category: 'Las llegadoras' },
    { title: 'La Bikina', artist: 'Luis Miguel', category: 'Las llegadoras' },
    { title: 'Moño Negro', artist: 'Conjunto Primavera', category: 'Las llegadoras' },
    { title: 'Tú Lo Decidiste', artist: 'Ana Gabriel', category: 'Las llegadoras' },
    { title: 'Luna', artist: 'Juan Gabriel', category: 'Las llegadoras' },
    { title: 'Demasiado Tarde', artist: 'Ana Gabriel', category: 'Las llegadoras' },
    { title: 'Qué de Raro Tiene', artist: 'Vicente Fernández', category: 'Las llegadoras' },
    { title: 'De Qué Maner Te Olvido', artist: 'Vicente Fernández', category: 'Las llegadoras' },
    { title: 'Cruz de Olvido', artist: 'Vicente Fernández', category: 'Las llegadoras' },
    { title: 'Nube Viajera', artist: 'Alejandro Fernández', category: 'Las llegadoras' },
    { title: 'El Golpe Traidor', artist: 'Bronco', category: 'Las llegadoras' },
    { title: 'Fue Un Placer Conocerte', artist: 'Juan Gabriel ', category: 'Las llegadoras' },
    { title: 'Aunque Mal Paguen Ellas', artist: 'Vicente Fernández', category: 'Las llegadoras' },
    { title: 'A tráves del Vaso', artist: 'Banda Los Sebastianes', category: 'Las llegadoras' },
    { title: 'Acá Entre Nos', artist: 'Vicente Fernández', category: 'Las llegadoras' },

    { title: 'El Mariachi Loco', artist: 'Tradicional', category: 'Echando bailongo' },
    { title: 'El Mono de Alambre', artist: 'Tradicional', category: 'Echando bailongo' },
    { title: 'Matálas', artist: 'Alejandro Fernández', category: 'Echando bailongo' },
    { title: 'Que Chulada de Mujer', artist: 'Vicente Fernández', category: 'Echando bailongo' },
    { title: 'Mi Gusto Es', artist: 'Antonio Aguilar', category: 'Echando bailongo' },
    { title: 'Flor de Capomo', artist: 'Los Cadetes de Linares', category: 'Echando bailongo' },
    { title: 'Que Nadie Sepa Mi Sufrir', artist: 'La Sonora Dinamita', category: 'Echando bailongo' },
    { title: 'La Media Naranja', artist: 'La Arrolladora Banda El Limón De René Camacho', category: 'Echando bailongo' },
    { title: 'La Boda del Huitlacoche', artist: 'Carin León y Los Honorables', category: 'Echando bailongo' },
    { title: 'Niño Perdido', artist: 'Banda El Recodo', category: 'Echando bailongo' },
    { title: 'La Chona', artist: 'Los Tucanes De Tijuana', category: 'Echando bailongo' },
    { title: "Camarón Pelao'", artist: 'Banda El Recodo', category: 'Echando bailongo' },
    { title: 'La Culebra', artist: 'Banda Machos', category: 'Echando bailongo' },
    { title: 'Yo No Fui', artist: 'Pedro Fernández', category: 'Echando bailongo' },
    { title: 'La Bota', artist: 'Mi Banda El Mexicano', category: 'Echando bailongo' },
    { title: 'Provócame', artist: 'Banda Vallarta Show', category: 'Echando bailongo' },
    { title: 'No Bailes de Caballito', artist: 'Mi Banda El Mexicano', category: 'Echando bailongo' },
    { title: 'La Bala', artist: 'Pedro Fernández', category: 'Echando bailongo' },
    { title: 'El Camaleón', artist: 'Tigrillos', category: 'Echando bailongo' },
    { title: 'El Ranchero Chido', artist: 'Los Huracanes Del Norte', category: 'Echando bailongo' },
    { title: 'El Pipiripau', artist: 'Los Plebeyos', category: 'Echando bailongo' },
    { title: 'Sergio El Bailador', artist: 'Bronco', category: 'Echando bailongo' },
    { title: 'El Tao Tao', artist: 'Grupo Control', category: 'Echando bailongo' },
    { title: 'La Yaquecita', artist: 'Los Tigres Del Norte', category: 'Echando bailongo' },

    { title: 'Caminos de Michoacán', artist: 'Federico Villa', category: 'Para recordar mis ayeres' },
    { title: 'Solamente Una Vez', artist: 'Luis Miguel', category: 'Para recordar mis ayeres' },
    { title: 'Luna de Octubre', artist: 'Pedro Infante', category: 'Para recordar mis ayeres' },
    { title: 'Cielito Lindo', artist: 'Pedro Infante', category: 'Para recordar mis ayeres' },
    { title: 'El Andariego', artist: 'Juan Carlos Hurtado', category: 'Para recordar mis ayeres' },
    { title: 'Payaso', artist: 'José José ', category: 'Para recordar mis ayeres' },
    { title: 'Sombras', artist: 'Julio Jaramillo', category: 'Para recordar mis ayeres' },
    { title: 'Llorarás', artist: "Oscar D'León", category: 'Para recordar mis ayeres' },
    { title: 'Luz de Luna', artist: 'Javier Solís', category: 'Para recordar mis ayeres' },
    { title: 'Caminos de Guanajuato', artist: 'José Alfredo Jiménez', category: 'Para recordar mis ayeres' },
    { title: 'Gracias', artist: 'José Alfredo Jiménez', category: 'Para recordar mis ayeres' },
    { title: 'Juráme', artist: 'Luis Miguel', category: 'Para recordar mis ayeres' },
    { title: 'Despacito, Muy Despacito', artist: 'Pedro Infante', category: 'Para recordar mis ayeres' },
    { title: 'Mi Tesoro', artist: 'Ramón Ayala', category: 'Para recordar mis ayeres' },
    { title: 'Esclavo y Amo', artist: 'Javier Solís', category: 'Para recordar mis ayeres' },
    { title: 'Quién', artist: 'Pedro Fernández', category: 'Para recordar mis ayeres' },
    { title: 'En Mi Viejo San Juan', artist: 'Javier Solís', category: 'Para recordar mis ayeres' },
    { title: 'Canta, Canta, Canta', artist: 'José Alfredo Jiménez', category: 'Para recordar mis ayeres' },
    { title: 'La Llorona', artist: 'Chavela Vargas', category: 'Para recordar mis ayeres' },
    { title: 'Como Han Pasado Los Años', artist: 'Rocío Dúrcal', category: 'Para recordar mis ayeres' },
    { title: 'Señora, Señora', artist: 'Denisse de Kalafe', category: 'Para recordar mis ayeres' },
    { title: 'Canto a la Madre', artist: 'Pedro Fernández', category: 'Para recordar mis ayeres' },
    { title: 'Tristes Recuerdos', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },
    { title: 'Por Un Amor', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'Qué Manera de Perder', artist: 'Ana Gabriel', category: 'Para recordar mis ayeres' },
    { title: 'Parece Que Fue Ayer', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'La Mesera', artist: 'Luis y Julián', category: 'Para recordar mis ayeres' },
    { title: 'El Tapatío', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'Indita Mía', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },
    { title: 'La Muerte de un Gallero', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'El Arrancadas', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'Adorado Tormento', artist: 'Vicente Fernández', category: 'Para recordar mis ayeres' },
    { title: 'Las Bodas de Luis Alonso', artist: 'Mariachi Vargas', category: 'Para recordar mis ayeres' },
    { title: 'Por Esa Calle Vive', artist: 'Los Barón de Apodaca', category: 'Para recordar mis ayeres' },
    { title: 'Bonita Finca de Adobe', artist: 'Ramón Ayala', category: 'Para recordar mis ayeres' },
    { title: 'Máquina 501', artist: 'El Charro Avita', category: 'Para recordar mis ayeres' },
    { title: 'El Coyote', artist: 'José Alfredo Jiménez', category: 'Para recordar mis ayeres' },
    { title: 'Valente Quintero', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },
    { title: 'La Martina', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },
    { title: 'Carabela', artist: 'Javier Solís', category: 'Para recordar mis ayeres' },
    { title: 'Caballo Prieto Azabache', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },
    { title: 'El Moro de Cumpas', artist: 'Antonio Aguilar', category: 'Para recordar mis ayeres' },

    { title: 'La Guadalupana', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Alzar las Manos', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Cien Ovejas', artist: 'Yesenia Flores', category: 'Canciones para misa' },
    { title: 'El Alfarero', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Sumérgeme', artist: 'Jesús Adrián Romero', category: 'Canciones para misa' },
    { title: 'Dios Está Aquí', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Ángeles', artist: 'Ángeles', category: 'Canciones para misa' },
    { title: 'Las Bodas de Caná', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Señor Ten Piedad de Nosotros', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Gloria', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Aleluya', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Ofertorio', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Cordero de Dios', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Santo', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Padre Nuestro', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Ángelus', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Nadie Te Ama Como Yo', artist: 'Martín Valverde', category: 'Canciones para misa' },
    { title: 'El Amor de Dios es Maravilloso', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Caminaré', artist: 'Juan A. Espinoza', category: 'Canciones para misa' },
    { title: 'El Pescador de Hombres', artist: 'Alabanzas A Cristo', category: 'Canciones para misa' },
    { title: 'Que Alegría Cuando Me Dijeron', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Mi Virgen Bella', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'Mi Virgen Ranchera', artist: 'Mariachi Vargas de Tecalitlán', category: 'Canciones para misa' },
    { title: 'Himno a la Humildad', artist: 'Los Bukis y Marco Antonio Solís ', category: 'Canciones para misa' },
    { title: 'La Manda', artist: 'Federico Villa', category: 'Canciones para misa' },
    { title: 'Niña', artist: 'Tradicional', category: 'Canciones para misa' },
    { title: 'La Espiga', artist: 'Tradicional', category: 'Canciones para misa' },

    { title: 'Amor Eterno', artist: 'Rocío Durcal', category: 'Una última despedida' },
    { title: 'Tu Voz', artist: 'Javier Solís', category: 'Una última despedida' },
    { title: 'Puño de Tierra', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Yo Te Extrañaré', artist: 'Tercer Cielo', category: 'Una última despedida' },
    { title: 'Te Vas Ángel Mío', artist: 'Ramón Ayala', category: 'Una última despedida' },
    { title: 'Las Golondrinas', artist: 'Mariachi Vargas de Tecalitlán', category: 'Una última despedida' },
    { title: 'Despedida Con Mariachi', artist: 'Los Cadetes de Linares', category: 'Una última despedida' },
    { title: 'Me Voy, Me Voy', artist: 'Los Cadetes de Linares', category: 'Una última despedida' },
    { title: 'El Día Que Me Muera', artist: ' Grupo Exterminador', category: 'Una última despedida' },
    { title: 'Que Me Entierren Con Mariachi', artist: 'Walter Villatoro', category: 'Una última despedida' },
    { title: 'Mi Último Deseo', artist: 'Banda Los Recoditos', category: 'Una última despedida' },
    { title: 'Cruz de Olvido', artist: 'Vicente Fernández', category: 'Una última despedida' },
    { title: 'Por El Amor a Mi Madre', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Nadie Es Eterno', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Descansa Mi Amor', artist: 'El Komander', category: 'Una última despedida' },
    { title: 'Cruz de Madera', artist: 'Ramón Ayala', category: 'Una última despedida' },
    { title: 'No Volveré', artist: 'Pedro Infante', category: 'Una última despedida' },
    { title: 'Que Me Entierren con la Banda', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Recuerdame Bonito', artist: 'Joan Sebastian', category: 'Una última despedida' },
    { title: 'Somos Los Que Somos', artist: 'Banda MS', category: 'Una última despedida' },
    { title: 'Cruz de Madera de la Más Corriente', artist: 'Ramón Ayala', category: 'Una última despedida' },
    { title: 'Mi Golondrina', artist: 'Ramón Ayala', category: 'Una última despedida' },
    { title: 'Que Falta Me Hace Mi Padre', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Mi Querido Viejo', artist: 'Vicente Fernández', category: 'Una última despedida' },
    { title: 'Cuando Dos Almas', artist: 'Los Caminantes', category: 'Una última despedida' },
    { title: 'Dos Coronas a Mi Madre', artist: 'Los Cadetes de Linares', category: 'Una última despedida' },
    { title: 'Siempre Hace Frío', artist: 'Linda Ronstadt', category: 'Una última despedida' },
    { title: 'El Hombre Que Más Te Amo', artist: 'Vicente Fernández', category: 'Una última despedida' },
    { title: 'Adiós a la Vida', artist: 'Vicente Fernández', category: 'Una última despedida' },
    { title: 'Échenme la Tierra Encima', artist: 'Pedro Infante', category: 'Una última despedida' },
    { title: 'La Barca de Oro', artist: 'Pedro Infante', category: 'Una última despedida' },
    { title: 'Dónde Estás Corazón', artist: 'Mocedades', category: 'Una última despedida' },
    { title: 'Ni Por Mil Puñados de Oro', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Cuatro Velas', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Camino al Cielo', artist: 'Vicente Fernández', category: 'Una última despedida' },
    { title: 'Mi Viejo', artist: 'Piero', category: 'Una última despedida' },
    { title: 'El Señor de las Canas', artist: 'Lorenzo de Monteclaro', category: 'Una última despedida' },
    { title: 'Tata Dios', artist: 'Miguel Aceves Mejía', category: 'Una última despedida' },
    { title: 'La Muerte Del Palomo', artist: 'Juan Gabriel', category: 'Una última despedida' },
    { title: 'Cuatro Milpas', artist: 'Antonio Aguilar', category: 'Una última despedida' },
    { title: 'Cuatro Cirios', artist: 'Javier Solís', category: 'Una última despedida' },
    { title: 'Gracias', artist: 'José Alfredo Jiménez', category: 'Una última despedida' },
  ];

  selectedCategory = this.categories[0];
  filteredSongs: any[] = [];

  ngOnInit() {
    this.filterSongs();
  }

  selectCategory(category: string) {
    this.selectedCategory = category;
    this.filterSongs();
  }

  filterSongs() {
    this.filteredSongs = this.songs.filter(
      (song) => song.category === this.selectedCategory
    );
  }
}
